USE [master]
GO
/****** Object:  Database [GestionDeEmpleados]    Script Date: 7/6/2024 18:08:07 ******/
CREATE DATABASE [GestionDeEmpleados]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GestionDeEmpleados', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\GestionDeEmpleados.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GestionDeEmpleados_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\GestionDeEmpleados_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [GestionDeEmpleados] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GestionDeEmpleados].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GestionDeEmpleados] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GestionDeEmpleados] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GestionDeEmpleados] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GestionDeEmpleados] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GestionDeEmpleados] SET ARITHABORT OFF 
GO
ALTER DATABASE [GestionDeEmpleados] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GestionDeEmpleados] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GestionDeEmpleados] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GestionDeEmpleados] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GestionDeEmpleados] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GestionDeEmpleados] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GestionDeEmpleados] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GestionDeEmpleados] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GestionDeEmpleados] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GestionDeEmpleados] SET  DISABLE_BROKER 
GO
ALTER DATABASE [GestionDeEmpleados] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GestionDeEmpleados] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GestionDeEmpleados] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GestionDeEmpleados] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GestionDeEmpleados] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GestionDeEmpleados] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GestionDeEmpleados] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GestionDeEmpleados] SET RECOVERY FULL 
GO
ALTER DATABASE [GestionDeEmpleados] SET  MULTI_USER 
GO
ALTER DATABASE [GestionDeEmpleados] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GestionDeEmpleados] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GestionDeEmpleados] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GestionDeEmpleados] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GestionDeEmpleados] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GestionDeEmpleados] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'GestionDeEmpleados', N'ON'
GO
ALTER DATABASE [GestionDeEmpleados] SET QUERY_STORE = ON
GO
ALTER DATABASE [GestionDeEmpleados] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [GestionDeEmpleados]
GO
/****** Object:  Table [dbo].[Empleado]    Script Date: 7/6/2024 18:08:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Empleado](
	[idEmpleado] [int] IDENTITY(1,1) NOT NULL,
	[NombreCompleto] [nvarchar](100) NOT NULL,
	[idSucursal] [int] NOT NULL,
 CONSTRAINT [PK_Empleado] PRIMARY KEY CLUSTERED 
(
	[idEmpleado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Sucursal]    Script Date: 7/6/2024 18:08:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sucursal](
	[idSucursal] [int] IDENTITY(1,1) NOT NULL,
	[Direccion] [nvarchar](100) NOT NULL,
	[Eliminada] [bit] NOT NULL,
 CONSTRAINT [PK_Sucursal] PRIMARY KEY CLUSTERED 
(
	[idSucursal] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Empleado]  WITH CHECK ADD  CONSTRAINT [FK_Empleado_Sucursal] FOREIGN KEY([idSucursal])
REFERENCES [dbo].[Sucursal] ([idSucursal])
GO
ALTER TABLE [dbo].[Empleado] CHECK CONSTRAINT [FK_Empleado_Sucursal]
GO
USE [master]
GO
ALTER DATABASE [GestionDeEmpleados] SET  READ_WRITE 
GO
